
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("b9088e76-738f-4f62-844f-b63be8c40955")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("QLXeModel", "FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_NhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(tbl_NhanVien), "tbl_MuonTraXe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(tbl_MuonTraXe), True)>
<Assembly: EdmRelationshipAttribute("QLXeModel", "FK_tbl_MuonTraXe_tbl_Xe", "tbl_Xe", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(tbl_Xe), "tbl_MuonTraXe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(tbl_MuonTraXe), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class QLXeModels
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new QLXeModels object using the connection string found in the 'QLXeModels' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=QLXeModels", "QLXeModels")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new QLXeModels object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "QLXeModels")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new QLXeModels object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "QLXeModels")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Appointments() As ObjectSet(Of Appointment)
        Get
            If (_Appointments Is Nothing) Then
                _Appointments = MyBase.CreateObjectSet(Of Appointment)("Appointments")
            End If
            Return _Appointments
        End Get
    End Property

    Private _Appointments As ObjectSet(Of Appointment)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Resources() As ObjectSet(Of Resource)
        Get
            If (_Resources Is Nothing) Then
                _Resources = MyBase.CreateObjectSet(Of Resource)("Resources")
            End If
            Return _Resources
        End Get
    End Property

    Private _Resources As ObjectSet(Of Resource)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property sysdiagrams() As ObjectSet(Of sysdiagram)
        Get
            If (_sysdiagrams Is Nothing) Then
                _sysdiagrams = MyBase.CreateObjectSet(Of sysdiagram)("sysdiagrams")
            End If
            Return _sysdiagrams
        End Get
    End Property

    Private _sysdiagrams As ObjectSet(Of sysdiagram)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tbl_MuonTraXe() As ObjectSet(Of tbl_MuonTraXe)
        Get
            If (_tbl_MuonTraXe Is Nothing) Then
                _tbl_MuonTraXe = MyBase.CreateObjectSet(Of tbl_MuonTraXe)("tbl_MuonTraXe")
            End If
            Return _tbl_MuonTraXe
        End Get
    End Property

    Private _tbl_MuonTraXe As ObjectSet(Of tbl_MuonTraXe)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tbl_NhanVien() As ObjectSet(Of tbl_NhanVien)
        Get
            If (_tbl_NhanVien Is Nothing) Then
                _tbl_NhanVien = MyBase.CreateObjectSet(Of tbl_NhanVien)("tbl_NhanVien")
            End If
            Return _tbl_NhanVien
        End Get
    End Property

    Private _tbl_NhanVien As ObjectSet(Of tbl_NhanVien)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tbl_Xe() As ObjectSet(Of tbl_Xe)
        Get
            If (_tbl_Xe Is Nothing) Then
                _tbl_Xe = MyBase.CreateObjectSet(Of tbl_Xe)("tbl_Xe")
            End If
            Return _tbl_Xe
        End Get
    End Property

    Private _tbl_Xe As ObjectSet(Of tbl_Xe)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Appointments EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAppointments(ByVal appointment As Appointment)
        MyBase.AddObject("Appointments", appointment)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Resources EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToResources(ByVal resource As Resource)
        MyBase.AddObject("Resources", resource)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTosysdiagrams(ByVal sysdiagram As sysdiagram)
        MyBase.AddObject("sysdiagrams", sysdiagram)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tbl_MuonTraXe EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotbl_MuonTraXe(ByVal tbl_MuonTraXe As tbl_MuonTraXe)
        MyBase.AddObject("tbl_MuonTraXe", tbl_MuonTraXe)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tbl_NhanVien EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotbl_NhanVien(ByVal tbl_NhanVien As tbl_NhanVien)
        MyBase.AddObject("tbl_NhanVien", tbl_NhanVien)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tbl_Xe EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotbl_Xe(ByVal tbl_Xe As tbl_Xe)
        MyBase.AddObject("tbl_Xe", tbl_Xe)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLXeModel", Name:="Appointment")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Appointment
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Appointment object.
    ''' </summary>
    ''' <param name="uniqueID">Initial value of the UniqueID property.</param>
    Public Shared Function CreateAppointment(uniqueID As Global.System.Int32) As Appointment
        Dim appointment as Appointment = New Appointment
        appointment.UniqueID = uniqueID
        Return appointment
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UniqueID() As Global.System.Int32
        Get
            Return _UniqueID
        End Get
        Set
            If (_UniqueID <> Value) Then
                OnUniqueIDChanging(value)
                ReportPropertyChanging("UniqueID")
                _UniqueID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("UniqueID")
                OnUniqueIDChanged()
            End If
        End Set
    End Property

    Private _UniqueID As Global.System.Int32
    Private Partial Sub OnUniqueIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnUniqueIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Type() As Nullable(Of Global.System.Int32)
        Get
            Return _Type
        End Get
        Set
            OnTypeChanging(value)
            ReportPropertyChanging("Type")
            _Type = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Type")
            OnTypeChanged()
        End Set
    End Property

    Private _Type As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTypeChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTypeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property StartDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _StartDate
        End Get
        Set
            OnStartDateChanging(value)
            ReportPropertyChanging("StartDate")
            _StartDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StartDate")
            OnStartDateChanged()
        End Set
    End Property

    Private _StartDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnStartDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnStartDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EndDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _EndDate
        End Get
        Set
            OnEndDateChanging(value)
            ReportPropertyChanging("EndDate")
            _EndDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EndDate")
            OnEndDateChanged()
        End Set
    End Property

    Private _EndDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEndDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEndDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property AllDay() As Nullable(Of Global.System.Boolean)
        Get
            Return _AllDay
        End Get
        Set
            OnAllDayChanging(value)
            ReportPropertyChanging("AllDay")
            _AllDay = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AllDay")
            OnAllDayChanged()
        End Set
    End Property

    Private _AllDay As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnAllDayChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnAllDayChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Subject() As Global.System.String
        Get
            Return _Subject
        End Get
        Set
            OnSubjectChanging(value)
            ReportPropertyChanging("Subject")
            _Subject = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Subject")
            OnSubjectChanged()
        End Set
    End Property

    Private _Subject As Global.System.String
    Private Partial Sub OnSubjectChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSubjectChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Location() As Global.System.String
        Get
            Return _Location
        End Get
        Set
            OnLocationChanging(value)
            ReportPropertyChanging("Location")
            _Location = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Location")
            OnLocationChanged()
        End Set
    End Property

    Private _Location As Global.System.String
    Private Partial Sub OnLocationChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLocationChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property

    Private _Description As Global.System.String
    Private Partial Sub OnDescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Status() As Nullable(Of Global.System.Int32)
        Get
            Return _Status
        End Get
        Set
            OnStatusChanging(value)
            ReportPropertyChanging("Status")
            _Status = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Status")
            OnStatusChanged()
        End Set
    End Property

    Private _Status As Nullable(Of Global.System.Int32)
    Private Partial Sub OnStatusChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Label() As Nullable(Of Global.System.Int32)
        Get
            Return _Label
        End Get
        Set
            OnLabelChanging(value)
            ReportPropertyChanging("Label")
            _Label = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Label")
            OnLabelChanged()
        End Set
    End Property

    Private _Label As Nullable(Of Global.System.Int32)
    Private Partial Sub OnLabelChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnLabelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ResourceID() As Nullable(Of Global.System.Int32)
        Get
            Return _ResourceID
        End Get
        Set
            OnResourceIDChanging(value)
            ReportPropertyChanging("ResourceID")
            _ResourceID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ResourceID")
            OnResourceIDChanged()
        End Set
    End Property

    Private _ResourceID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnResourceIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnResourceIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ResourceIDs() As Global.System.String
        Get
            Return _ResourceIDs
        End Get
        Set
            OnResourceIDsChanging(value)
            ReportPropertyChanging("ResourceIDs")
            _ResourceIDs = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ResourceIDs")
            OnResourceIDsChanged()
        End Set
    End Property

    Private _ResourceIDs As Global.System.String
    Private Partial Sub OnResourceIDsChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnResourceIDsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ReminderInfo() As Global.System.String
        Get
            Return _ReminderInfo
        End Get
        Set
            OnReminderInfoChanging(value)
            ReportPropertyChanging("ReminderInfo")
            _ReminderInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ReminderInfo")
            OnReminderInfoChanged()
        End Set
    End Property

    Private _ReminderInfo As Global.System.String
    Private Partial Sub OnReminderInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReminderInfoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RecurrenceInfo() As Global.System.String
        Get
            Return _RecurrenceInfo
        End Get
        Set
            OnRecurrenceInfoChanging(value)
            ReportPropertyChanging("RecurrenceInfo")
            _RecurrenceInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RecurrenceInfo")
            OnRecurrenceInfoChanged()
        End Set
    End Property

    Private _RecurrenceInfo As Global.System.String
    Private Partial Sub OnRecurrenceInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRecurrenceInfoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CustomField1() As Global.System.String
        Get
            Return _CustomField1
        End Get
        Set
            OnCustomField1Changing(value)
            ReportPropertyChanging("CustomField1")
            _CustomField1 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CustomField1")
            OnCustomField1Changed()
        End Set
    End Property

    Private _CustomField1 As Global.System.String
    Private Partial Sub OnCustomField1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomField1Changed()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLXeModel", Name:="Resource")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Resource
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Resource object.
    ''' </summary>
    ''' <param name="uniqueID">Initial value of the UniqueID property.</param>
    ''' <param name="resourceID">Initial value of the ResourceID property.</param>
    Public Shared Function CreateResource(uniqueID As Global.System.Int32, resourceID As Global.System.Int32) As Resource
        Dim resource as Resource = New Resource
        resource.UniqueID = uniqueID
        resource.ResourceID = resourceID
        Return resource
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UniqueID() As Global.System.Int32
        Get
            Return _UniqueID
        End Get
        Set
            If (_UniqueID <> Value) Then
                OnUniqueIDChanging(value)
                ReportPropertyChanging("UniqueID")
                _UniqueID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("UniqueID")
                OnUniqueIDChanged()
            End If
        End Set
    End Property

    Private _UniqueID As Global.System.Int32
    Private Partial Sub OnUniqueIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnUniqueIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ResourceID() As Global.System.Int32
        Get
            Return _ResourceID
        End Get
        Set
            OnResourceIDChanging(value)
            ReportPropertyChanging("ResourceID")
            _ResourceID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ResourceID")
            OnResourceIDChanged()
        End Set
    End Property

    Private _ResourceID As Global.System.Int32
    Private Partial Sub OnResourceIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnResourceIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ResourceName() As Global.System.String
        Get
            Return _ResourceName
        End Get
        Set
            OnResourceNameChanging(value)
            ReportPropertyChanging("ResourceName")
            _ResourceName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ResourceName")
            OnResourceNameChanged()
        End Set
    End Property

    Private _ResourceName As Global.System.String
    Private Partial Sub OnResourceNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnResourceNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Color() As Nullable(Of Global.System.Int32)
        Get
            Return _Color
        End Get
        Set
            OnColorChanging(value)
            ReportPropertyChanging("Color")
            _Color = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Color")
            OnColorChanged()
        End Set
    End Property

    Private _Color As Nullable(Of Global.System.Int32)
    Private Partial Sub OnColorChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnColorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Image() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Image)
        End Get
        Set
            OnImageChanging(value)
            ReportPropertyChanging("Image")
            _Image = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Image")
            OnImageChanged()
        End Set
    End Property

    Private _Image As Global.System.Byte()
    Private Partial Sub OnImageChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnImageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CustomField1() As Global.System.String
        Get
            Return _CustomField1
        End Get
        Set
            OnCustomField1Changing(value)
            ReportPropertyChanging("CustomField1")
            _CustomField1 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CustomField1")
            OnCustomField1Changed()
        End Set
    End Property

    Private _CustomField1 As Global.System.String
    Private Partial Sub OnCustomField1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomField1Changed()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLXeModel", Name:="sysdiagram")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class sysdiagram
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new sysdiagram object.
    ''' </summary>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="principal_id">Initial value of the principal_id property.</param>
    ''' <param name="diagram_id">Initial value of the diagram_id property.</param>
    Public Shared Function Createsysdiagram(name As Global.System.String, principal_id As Global.System.Int32, diagram_id As Global.System.Int32) As sysdiagram
        Dim sysdiagram as sysdiagram = New sysdiagram
        sysdiagram.name = name
        sysdiagram.principal_id = principal_id
        sysdiagram.diagram_id = diagram_id
        Return sysdiagram
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property principal_id() As Global.System.Int32
        Get
            Return _principal_id
        End Get
        Set
            Onprincipal_idChanging(value)
            ReportPropertyChanging("principal_id")
            _principal_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("principal_id")
            Onprincipal_idChanged()
        End Set
    End Property

    Private _principal_id As Global.System.Int32
    Private Partial Sub Onprincipal_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onprincipal_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property diagram_id() As Global.System.Int32
        Get
            Return _diagram_id
        End Get
        Set
            If (_diagram_id <> Value) Then
                Ondiagram_idChanging(value)
                ReportPropertyChanging("diagram_id")
                _diagram_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("diagram_id")
                Ondiagram_idChanged()
            End If
        End Set
    End Property

    Private _diagram_id As Global.System.Int32
    Private Partial Sub Ondiagram_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondiagram_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property version() As Nullable(Of Global.System.Int32)
        Get
            Return _version
        End Get
        Set
            OnversionChanging(value)
            ReportPropertyChanging("version")
            _version = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("version")
            OnversionChanged()
        End Set
    End Property

    Private _version As Nullable(Of Global.System.Int32)
    Private Partial Sub OnversionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnversionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property definition() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_definition)
        End Get
        Set
            OndefinitionChanging(value)
            ReportPropertyChanging("definition")
            _definition = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("definition")
            OndefinitionChanged()
        End Set
    End Property

    Private _definition As Global.System.Byte()
    Private Partial Sub OndefinitionChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OndefinitionChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLXeModel", Name:="tbl_MuonTraXe")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tbl_MuonTraXe
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tbl_MuonTraXe object.
    ''' </summary>
    ''' <param name="maMuon">Initial value of the MaMuon property.</param>
    Public Shared Function Createtbl_MuonTraXe(maMuon As Global.System.Int32) As tbl_MuonTraXe
        Dim tbl_MuonTraXe as tbl_MuonTraXe = New tbl_MuonTraXe
        tbl_MuonTraXe.MaMuon = maMuon
        Return tbl_MuonTraXe
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MaMuon() As Global.System.Int32
        Get
            Return _MaMuon
        End Get
        Set
            If (_MaMuon <> Value) Then
                OnMaMuonChanging(value)
                ReportPropertyChanging("MaMuon")
                _MaMuon = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("MaMuon")
                OnMaMuonChanged()
            End If
        End Set
    End Property

    Private _MaMuon As Global.System.Int32
    Private Partial Sub OnMaMuonChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnMaMuonChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MaNV() As Global.System.String
        Get
            Return _MaNV
        End Get
        Set
            OnMaNVChanging(value)
            ReportPropertyChanging("MaNV")
            _MaNV = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MaNV")
            OnMaNVChanged()
        End Set
    End Property

    Private _MaNV As Global.System.String
    Private Partial Sub OnMaNVChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMaNVChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BienSo() As Global.System.String
        Get
            Return _BienSo
        End Get
        Set
            OnBienSoChanging(value)
            ReportPropertyChanging("BienSo")
            _BienSo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("BienSo")
            OnBienSoChanged()
        End Set
    End Property

    Private _BienSo As Global.System.String
    Private Partial Sub OnBienSoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBienSoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NgayDkMuon() As Nullable(Of Global.System.DateTime)
        Get
            Return _NgayDkMuon
        End Get
        Set
            OnNgayDkMuonChanging(value)
            ReportPropertyChanging("NgayDkMuon")
            _NgayDkMuon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("NgayDkMuon")
            OnNgayDkMuonChanged()
        End Set
    End Property

    Private _NgayDkMuon As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnNgayDkMuonChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnNgayDkMuonChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ThoiGianMuon() As Nullable(Of Global.System.DateTime)
        Get
            Return _ThoiGianMuon
        End Get
        Set
            OnThoiGianMuonChanging(value)
            ReportPropertyChanging("ThoiGianMuon")
            _ThoiGianMuon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ThoiGianMuon")
            OnThoiGianMuonChanged()
        End Set
    End Property

    Private _ThoiGianMuon As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnThoiGianMuonChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnThoiGianMuonChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ThoiGianTra() As Nullable(Of Global.System.DateTime)
        Get
            Return _ThoiGianTra
        End Get
        Set
            OnThoiGianTraChanging(value)
            ReportPropertyChanging("ThoiGianTra")
            _ThoiGianTra = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ThoiGianTra")
            OnThoiGianTraChanged()
        End Set
    End Property

    Private _ThoiGianTra As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnThoiGianTraChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnThoiGianTraChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MucDich() As Global.System.String
        Get
            Return _MucDich
        End Get
        Set
            OnMucDichChanging(value)
            ReportPropertyChanging("MucDich")
            _MucDich = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MucDich")
            OnMucDichChanged()
        End Set
    End Property

    Private _MucDich As Global.System.String
    Private Partial Sub OnMucDichChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMucDichChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DiaDiemDen() As Global.System.String
        Get
            Return _DiaDiemDen
        End Get
        Set
            OnDiaDiemDenChanging(value)
            ReportPropertyChanging("DiaDiemDen")
            _DiaDiemDen = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DiaDiemDen")
            OnDiaDiemDenChanged()
        End Set
    End Property

    Private _DiaDiemDen As Global.System.String
    Private Partial Sub OnDiaDiemDenChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDiaDiemDenChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SoKmDongHo() As Global.System.String
        Get
            Return _SoKmDongHo
        End Get
        Set
            OnSoKmDongHoChanging(value)
            ReportPropertyChanging("SoKmDongHo")
            _SoKmDongHo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SoKmDongHo")
            OnSoKmDongHoChanged()
        End Set
    End Property

    Private _SoKmDongHo As Global.System.String
    Private Partial Sub OnSoKmDongHoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSoKmDongHoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SoKmDaDi() As Global.System.String
        Get
            Return _SoKmDaDi
        End Get
        Set
            OnSoKmDaDiChanging(value)
            ReportPropertyChanging("SoKmDaDi")
            _SoKmDaDi = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SoKmDaDi")
            OnSoKmDaDiChanged()
        End Set
    End Property

    Private _SoKmDaDi As Global.System.String
    Private Partial Sub OnSoKmDaDiChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSoKmDaDiChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TinhTrang() As Nullable(Of Global.System.Int32)
        Get
            Return _TinhTrang
        End Get
        Set
            OnTinhTrangChanging(value)
            ReportPropertyChanging("TinhTrang")
            _TinhTrang = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TinhTrang")
            OnTinhTrangChanged()
        End Set
    End Property

    Private _TinhTrang As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTinhTrangChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTinhTrangChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MoTa() As Global.System.String
        Get
            Return _MoTa
        End Get
        Set
            OnMoTaChanging(value)
            ReportPropertyChanging("MoTa")
            _MoTa = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MoTa")
            OnMoTaChanged()
        End Set
    End Property

    Private _MoTa As Global.System.String
    Private Partial Sub OnMoTaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMoTaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BienSoCu() As Global.System.String
        Get
            Return _BienSoCu
        End Get
        Set
            OnBienSoCuChanging(value)
            ReportPropertyChanging("BienSoCu")
            _BienSoCu = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("BienSoCu")
            OnBienSoCuChanged()
        End Set
    End Property

    Private _BienSoCu As Global.System.String
    Private Partial Sub OnBienSoCuChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBienSoCuChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLXeModel", "FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_NhanVien")>
    Public Property tbl_NhanVien() As tbl_NhanVien
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tbl_NhanVien)("QLXeModel.FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_NhanVien").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tbl_NhanVien)("QLXeModel.FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_NhanVien").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tbl_NhanVienReference() As EntityReference(Of tbl_NhanVien)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tbl_NhanVien)("QLXeModel.FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_NhanVien")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of tbl_NhanVien)("QLXeModel.FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_NhanVien", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLXeModel", "FK_tbl_MuonTraXe_tbl_Xe", "tbl_Xe")>
    Public Property tbl_Xe() As tbl_Xe
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tbl_Xe)("QLXeModel.FK_tbl_MuonTraXe_tbl_Xe", "tbl_Xe").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tbl_Xe)("QLXeModel.FK_tbl_MuonTraXe_tbl_Xe", "tbl_Xe").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tbl_XeReference() As EntityReference(Of tbl_Xe)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tbl_Xe)("QLXeModel.FK_tbl_MuonTraXe_tbl_Xe", "tbl_Xe")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of tbl_Xe)("QLXeModel.FK_tbl_MuonTraXe_tbl_Xe", "tbl_Xe", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLXeModel", Name:="tbl_NhanVien")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tbl_NhanVien
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tbl_NhanVien object.
    ''' </summary>
    ''' <param name="maNV">Initial value of the MaNV property.</param>
    Public Shared Function Createtbl_NhanVien(maNV As Global.System.String) As tbl_NhanVien
        Dim tbl_NhanVien as tbl_NhanVien = New tbl_NhanVien
        tbl_NhanVien.MaNV = maNV
        Return tbl_NhanVien
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MaNV() As Global.System.String
        Get
            Return _MaNV
        End Get
        Set
            If (_MaNV <> Value) Then
                OnMaNVChanging(value)
                ReportPropertyChanging("MaNV")
                _MaNV = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("MaNV")
                OnMaNVChanged()
            End If
        End Set
    End Property

    Private _MaNV As Global.System.String
    Private Partial Sub OnMaNVChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMaNVChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TenNV() As Global.System.String
        Get
            Return _TenNV
        End Get
        Set
            OnTenNVChanging(value)
            ReportPropertyChanging("TenNV")
            _TenNV = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TenNV")
            OnTenNVChanged()
        End Set
    End Property

    Private _TenNV As Global.System.String
    Private Partial Sub OnTenNVChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTenNVChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SoCMND() As Global.System.String
        Get
            Return _SoCMND
        End Get
        Set
            OnSoCMNDChanging(value)
            ReportPropertyChanging("SoCMND")
            _SoCMND = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SoCMND")
            OnSoCMNDChanged()
        End Set
    End Property

    Private _SoCMND As Global.System.String
    Private Partial Sub OnSoCMNDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSoCMNDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NgaySinh() As Nullable(Of Global.System.DateTime)
        Get
            Return _NgaySinh
        End Get
        Set
            OnNgaySinhChanging(value)
            ReportPropertyChanging("NgaySinh")
            _NgaySinh = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("NgaySinh")
            OnNgaySinhChanged()
        End Set
    End Property

    Private _NgaySinh As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnNgaySinhChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnNgaySinhChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property QueQuan() As Global.System.String
        Get
            Return _QueQuan
        End Get
        Set
            OnQueQuanChanging(value)
            ReportPropertyChanging("QueQuan")
            _QueQuan = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("QueQuan")
            OnQueQuanChanged()
        End Set
    End Property

    Private _QueQuan As Global.System.String
    Private Partial Sub OnQueQuanChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnQueQuanChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLXeModel", "FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_MuonTraXe")>
     Public Property tbl_MuonTraXe() As EntityCollection(Of tbl_MuonTraXe)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of tbl_MuonTraXe)("QLXeModel.FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_MuonTraXe")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of tbl_MuonTraXe)("QLXeModel.FK_tbl_MuonTraXe_tbl_NhanVien", "tbl_MuonTraXe", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLXeModel", Name:="tbl_Xe")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tbl_Xe
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tbl_Xe object.
    ''' </summary>
    ''' <param name="model">Initial value of the Model property.</param>
    ''' <param name="bienSo">Initial value of the BienSo property.</param>
    Public Shared Function Createtbl_Xe(model As Global.System.String, bienSo As Global.System.String) As tbl_Xe
        Dim tbl_Xe as tbl_Xe = New tbl_Xe
        tbl_Xe.Model = model
        tbl_Xe.BienSo = bienSo
        Return tbl_Xe
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TenXe() As Global.System.String
        Get
            Return _TenXe
        End Get
        Set
            OnTenXeChanging(value)
            ReportPropertyChanging("TenXe")
            _TenXe = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TenXe")
            OnTenXeChanged()
        End Set
    End Property

    Private _TenXe As Global.System.String
    Private Partial Sub OnTenXeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTenXeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Model() As Global.System.String
        Get
            Return _Model
        End Get
        Set
            OnModelChanging(value)
            ReportPropertyChanging("Model")
            _Model = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Model")
            OnModelChanged()
        End Set
    End Property

    Private _Model As Global.System.String
    Private Partial Sub OnModelChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MauXe() As Global.System.String
        Get
            Return _MauXe
        End Get
        Set
            OnMauXeChanging(value)
            ReportPropertyChanging("MauXe")
            _MauXe = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MauXe")
            OnMauXeChanged()
        End Set
    End Property

    Private _MauXe As Global.System.String
    Private Partial Sub OnMauXeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMauXeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SoCho() As Nullable(Of Global.System.Int32)
        Get
            Return _SoCho
        End Get
        Set
            OnSoChoChanging(value)
            ReportPropertyChanging("SoCho")
            _SoCho = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SoCho")
            OnSoChoChanged()
        End Set
    End Property

    Private _SoCho As Nullable(Of Global.System.Int32)
    Private Partial Sub OnSoChoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnSoChoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TinhTrang() As Nullable(Of Global.System.Int32)
        Get
            Return _TinhTrang
        End Get
        Set
            OnTinhTrangChanging(value)
            ReportPropertyChanging("TinhTrang")
            _TinhTrang = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TinhTrang")
            OnTinhTrangChanged()
        End Set
    End Property

    Private _TinhTrang As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTinhTrangChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTinhTrangChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BienSo() As Global.System.String
        Get
            Return _BienSo
        End Get
        Set
            If (_BienSo <> Value) Then
                OnBienSoChanging(value)
                ReportPropertyChanging("BienSo")
                _BienSo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("BienSo")
                OnBienSoChanged()
            End If
        End Set
    End Property

    Private _BienSo As Global.System.String
    Private Partial Sub OnBienSoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBienSoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SoKmHienTai() As Global.System.String
        Get
            Return _SoKmHienTai
        End Get
        Set
            OnSoKmHienTaiChanging(value)
            ReportPropertyChanging("SoKmHienTai")
            _SoKmHienTai = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SoKmHienTai")
            OnSoKmHienTaiChanged()
        End Set
    End Property

    Private _SoKmHienTai As Global.System.String
    Private Partial Sub OnSoKmHienTaiChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSoKmHienTaiChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLXeModel", "FK_tbl_MuonTraXe_tbl_Xe", "tbl_MuonTraXe")>
     Public Property tbl_MuonTraXe() As EntityCollection(Of tbl_MuonTraXe)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of tbl_MuonTraXe)("QLXeModel.FK_tbl_MuonTraXe_tbl_Xe", "tbl_MuonTraXe")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of tbl_MuonTraXe)("QLXeModel.FK_tbl_MuonTraXe_tbl_Xe", "tbl_MuonTraXe", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


